### ISSUE TITLE
Spelling error In the Concept Mapping section

### ISSUE THREAD

**Issue by jamiebillingham** [UCLALibrary/foundations#11]
In the Concept Mapping section:

Place a bubble in the middle of your notebook page labeled "memorable, **meangful**, and transformative learning."

In your notebook, rapidly brainstorm a concept map related to memorable, **meangful**, and transformative learning. There are many ways to do this, so feel free to explore your own approach, or to follow the suggestions below.

**Comment by dmcwo** [comment]
Thanks! Looks like someone fixed this at some point. Thanks!!
