### ISSUE TITLE
Build Something Toolkit is not accessable

### ISSUE THREAD

**Issue by jamiebillingham** [UCLALibrary/foundations#12]
The toolkit seems to have been removed from Box.com.

https://ucla.app.box.com/v/build-something-toolkit

**Comment by dmcwo** [comment]
Thanks for letting us know and so sorry for the slowww reply!!

The link from https://uclalibrary.github.io/foundations/modules/resources/toolkits/ has been updated to https://app.box.com/s/184451559ey5uloo11x42z458zcrlevp which seems to be working.

Thanks!
